# in case you need to use enviroment file with vagrant
require 'dotenv'
Dotenv.load
# and when useing env just use the variable like this ENV['VARIABLE_NAME']

Vagrant.configure("2") do |config|
  config.vm.define "mjarboua" do |mjarboua|
    mjarboua.vm.box = "bento/ubuntu-24.04"
    mjarboua.vm.hostname = ENV['FIRST_MACHINE_HOSTNAME']
    mjarboua.vm.network "private_network", ip: ENV['FIRST_MACHINE_IP_ADDRESS']
    mjarboua.vm.provider ENV['PROVIDER'] do |vb|
      vb.gui = false
      vb.memory = ENV['MEM']
      vb.cpus = ENV['CPUS']
    end
  end
  config.vm.define "mohamed" do |mohamed|
    mohamed.vm.box = "bento/ubuntu-24.04"
    mohamed.vm.hostname = ENV['SECOND_MACHINE_HOSTNAME']
    mohamed.vm.network "private_network", ip: ENV['SECOND_MACHINE_IP_ADDRESS']
    mohamed.vm.provider ENV['PROVIDER'] do |vb|
      vb.gui = false
      vb.memory = ENV['MEM']
      vb.cpus = ENV['CPUS']
    end
    mohamed.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      ufw allow 6443/tcp #apiserver
      ufw allow from 10.42.0.0/16 to any #pods
      ufw allow from 10.43.0.0/16 to any #services
      sudo apt-get install -y net-tools
    SHELL
  end
end

